//REFRESH TOKEN
export const REFRESH_FAIl = "REFRESH_FAIL";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
// login and register
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
//activation
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
//loading
export const SET_AUTH_LOADING = "SET_AUTH_LOADING ";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING ";

//Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
//load user
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIl = "USER_LOADED_FAIL";
//IS AUTHENTICATED
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIl = "AUTHENTICATED_FAIL";
//RESET PASSWEORD
export const RESET_PASSWORD_CONFIRM_FAIl = "RESET_PASSWORD_CONFIRM_FAIl";
export const RESET_PASSWORD_CONFIRM_SUCCESS = "RESET_PASSWORD_CONFIRM_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
//LOGOUT
export const LOGOUT = "LOGOUT";
// categories

export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

// Products
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS_BY_ARRIVAL_SUCCESS =
  "GET_PRODUCTS_BY_ARRIVAL_SUCCESS";
export const GET_PRODUCTS_BY_ARRIVAL_FAIL = "GET_PRODUCTS_BY_ARRIVAL_FAIL";

// vendidos
export const GET_PRODUCTS_BY_SOLD_SUCCESS = "GET_PRODUCTS_BY_SOLD_SUCCESS";
export const GET_PRODUCTS_BY_SOLD_FAIL = "GET_PRODUCTS_BY_SOLD_FAIL";
//detail prodcut
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
//search products
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS";
export const SEARCH_PRODUCTS_FAIL = "SEARCH_PRODUCTS_FAIL";
//related products
export const RELATED_PRODUCTS_SUCCESS = "RELATED_PRODUCTS_SUCCESS";
export const RELATED_PRODUCTS_FAIL = "RELATED_PRODUCTS_FAIL";
// filters products
export const FILTER_PRODUCTS_SUCCESS = "FILTER_PRODUCTS_SUCCESS";
export const FILTER_PRODUCTS_FAIL = "FILTER_PRODUCTS_FAIL";
