//REFRESH TOKEN
export const REFRESH_FAIl = "REFRESH_FAIL";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
// login and register
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
//activation
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
//loading
export const SET_AUTH_LOADING = "SET_AUTH_LOADING ";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING ";

//Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
//load user
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIl = "USER_LOADED_FAIL";
//IS AUTHENTICATED
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIl = "AUTHENTICATED_FAIL";
//RESET PASSWEORD
export const RESET_PASSWORD_CONFIRM_FAIl = "RESET_PASSWORD_CONFIRM_FAIl";
//LOGOUT
export const LOGOUT = "LOGOUT";
